### ISSUE TITLE
TypeError: no implicit conversion of Fixnum into String

### ISSUE THREAD

**Issue by andreasticket** [logstash-plugins/logstash-output-nagios_nsca#12] opened 2018-01-23 14:07 UTC
We are having problem with logstash-output-nagios_nsca and the latest version of Logstash 6.1.2

Centos7, Logstash Docker image

[2018-01-23T14:00:00,893][WARN ][logstash.outputs.nagiosnsca] Skipping nagios_nsca output; error calling send_nsca {:error=>#<TypeError: no implicit conversion of Fixnum into String>, :nagios_nsca_command=>"/usr/sbin/send_nsca -H <ip> -p 5667 -d : -c /usr/share/logstash/config/send_nsca.cfg", :message=>"test_salesws:OrderAdjustmentBatchService.autoAdjustInternetOrders TICKET_NO:0:Job finished sucessfully in PT0.568S", :missed_event=>#<LogStash::Event:0x76331c93>}

**Comment by jsvd** [comment] 2018-01-23 16:49
can you provide the configuration you're using ?

**Comment by andreasticket** [comment] 2018-01-24 07:16
```
FROM docker.elastic.co/logstash/logstash-oss:6.1.2

USER root:root
RUN yum install wget -y
RUN yum -y install epel-release

# Install NSCA client
RUN wget --output-document=nsca-client-2.9.2-1.el7.x86_64.rpm http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/n/nsca-client-2.9.2-1.el7.x86_64.rpm
RUN yum -y localinstall nsca-client-2.9.2-1.el7.x86_64.rpm

# Logstash
USER logstash:logstash
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
COPY --chown=logstash:logstash pipeline/ /usr/share/logstash/pipeline/
COPY --chown=logstash:logstash config/ /usr/share/logstash/config/
RUN bin/logstash-plugin install logstash-output-nagios_nsca


Pipeline config

input {
  tcp {
    port => 3334
    codec => "json_lines"
    tags => ["tcpLogs"]
  }
}

output {
  if [NagiosHost] {
    nagios_nsca {
      host => "#ip"
      send_nsca_config => "/usr/share/logstash/config/send_nsca.cfg"
      nagios_service => "%{jobName} %{MarketPlace}"
      nagios_host => "%{NagiosHost}"
			nagios_status => "%{NagiosStatus}"
			message_format => "%{message}"
    }
  }
}
```

**Comment by andreasticket** [comment] 2018-01-29 14:35
@jsvd any update on this? Do you need more info?

**Comment by liuthree** [comment] 2018-02-27 03:00
I met the same problem.Have you solved it？

**Comment by para6666** [comment] 2018-03-08 09:16
Hi,

change in the "nagios_nsca.rb"
config :port, :validate => :number, :default => 5667

to

config :port, :validate => :string, :default => 5667

of course you have to change the port config to:
port => "3334"

not sure if this a good idea, but it works

**Comment by joschi99** [comment] 2018-04-19 15:00
same problem on Logstash 6.2.4. Any idea how to resolve? I tried to change in "nagios_nsca.rb" from ":number" -> ":string", but always the same issue.

**Comment by usp-rol** [comment] 2018-05-04 06:00
@jsvd any news here? this seems to be a consistent failure as we can confirm the same bug here...

**Comment by tkorochka** [comment] 2018-05-04 06:57
@usp-rol , fix from @para6666 works for me.

**Comment by para6666** [comment] 2018-05-04 07:05
@joschi99 
Did you changed the port part in the output to a String?
port => "5667"

and did you restarted Logstash completely?

**Comment by usp-rol** [comment] 2018-05-04 09:33
sure, we can also confirm the workaround. but still it remains logstash 6.2 (at least) not supporting this plugin anymore (without making changes to ruby files, yes).

so the only issue here not making any progress was #13 
I hope this can be solved (merged) then. unfortunately jenkins tests are failing on current master branch (not really caused by the change from #13)

**Closed as completed** 2018-05-11 12:51 UTC
Labels: bug, unconfirmed, needs details

**Comment by nickjwest** [comment] 2019-05-24 11:46
Hi,

I am seeing this issue on logstash 6.7.1, i have tried the change to nagios_nsca.rb as specified above but it doesn't appear to be working. Error message as per below. Are there any other things to check to be able to workaround this as it will be very useful to me to get this working..?

Skipping nagios_nsca output; error calling send_nsca {:error=>#<TypeError: no implicit conversion of Integer into String>
